name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    name: Commit validation, build and test 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for commit history

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate commit messages
        run: |
          npx commitlint \
            --from=origin/${{ github.event.pull_request.base.ref }} \
            --to=HEAD \
            --verbose

      - name: Build project
        run: pnpm build

      - name: Run tests
        run: pnpm test --if-present
