name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  commitlint:
    name: Commit message validation

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22] # Only one, so it doesn't run multiple times
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for commit history

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # Needed for parallel jobs optimization

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate commit messages
        run: npx commitlint --from=origin/${{ github.base_ref }} --to=HEAD --verbose
  
  build:
    name: Build application
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # Needed for parallel jobs optimization

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

  test:
    name: Run tests suite

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # Needed for parallel jobs optimization

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test --if-present
